listener 8883 0.0.0.0
cafile /mosquitto/pki/ca.crt.pem
certfile /mosquitto/pki/mqtt-broker.crt.pem
keyfile /mosquitto/pki/mqtt-broker.key.pem
require_certificate true
use_identity_as_username true
allow_anonymous false
persistence true
persistence_location /mosquitto/data/
log_dest stdout
